/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class y_sizer_jni_StackSizeAccess */

#ifndef _Included_y_sizer_jni_StackSizeAccess
#define _Included_y_sizer_jni_StackSizeAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     y_sizer_jni_StackSizeAccess
 * Method:    getStackSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_y_sizer_jni_StackSizeAccess_getStackSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
